
package mdi;

import formularios.IniciarSesion;
import formularios.Menu;
import javax.swing.JOptionPane;
import modelos.Estudiante;
import tablas.Conexion;
import tablas.TablaEstudiante;
import tablas.TablaSuscripcion;

/**
 *
 * @author Antonio Meza
 */
public class NuevaSuscripcion extends javax.swing.JInternalFrame {

    Conexion conex = new Conexion();
    TablaEstudiante tlbEst = new TablaEstudiante(conex);
    TablaSuscripcion tlbSus = new TablaSuscripcion(conex);
    Estudiante est;
    IniciarSesion In;
    Menu jsmenu;
    
    public NuevaSuscripcion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Cb_Area = new javax.swing.JComboBox<>();
        JT_ConId = new javax.swing.JTextField();
        bSuscribirse = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setClosable(true);
        setTitle("Nueva Suscripción");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Escriba su ID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Seleccione el area");

        Cb_Area.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cb_Area.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Futbol sala", "Futbol  campo", "voleibol", "Judo", "Karate", "Musica", "Teatro", "Danza" }));
        Cb_Area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cb_AreaActionPerformed(evt);
            }
        });

        JT_ConId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JT_ConId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_ConIdActionPerformed(evt);
            }
        });

        bSuscribirse.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bSuscribirse.setText("Suscribirse");
        bSuscribirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSuscribirseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bSuscribirse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JT_ConId)
                            .addComponent(Cb_Area, 0, 181, Short.MAX_VALUE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JT_ConId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cb_Area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(bSuscribirse, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JT_ConIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_ConIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_ConIdActionPerformed

    private void Cb_AreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cb_AreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cb_AreaActionPerformed

    private void bSuscribirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSuscribirseActionPerformed
        // TODO add your handling code here:
       
       int s = tlbSus.agregarRegistro(JT_ConId.getText(), (String) Cb_Area.getSelectedItem(),true);
        if(s!=0){
            JOptionPane.showMessageDialog(null,"Se ha suscrito a " + Cb_Area.getSelectedItem() ,"Suscripcion", JOptionPane.INFORMATION_MESSAGE);
        }else {
            JOptionPane.showMessageDialog(this, "Usuario Incorrecto", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_bSuscribirseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cb_Area;
    private javax.swing.JTextField JT_ConId;
    private javax.swing.JButton bSuscribirse;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    // End of variables declaration//GEN-END:variables
}
